name = 'metochrist'
pages_build_output_dir = 'build/site'

[vars]
NODE_ENV = 'production'
BUN_VERSION = '1.3.1'
TURNSTILE_SITE_KEY = '0x4AAAAAAChflGkQqpN6zibF'
WORKER_URL = 'https://metochrist-worker-prod.dizzib-dev.workers.dev'

